module.exports = {
    general: {
        Cross: "appEmoji_carpi",
        Tik: "appEmoji_tik",
        Warning: "appEmoji_unlem",
        Woman: "appEmoji_kari",
        Man: "appEmoji_erkek",
        Category: "appEmoji_kategori",
        Time: "appEmoji_saat",
        Elmas: "appEmoji_elmas",
        Metin: "appEmoji_metin",
        Ses: "appEmoji_ses",
        Yayın: "appEmoji_yayin",
        Kamera: "appEmoji_kamera",
        Sagok: "appEmoji_sagOk",
        Solok: "appEmoji_solOk",
        Cop: "appEmoji_cop",
        Kup: "appEmoji_kup",
        Bir: "appEmoji_bir",
        İki: "appEmoji_iki",
        Uc: "appEmoji_uc",
        Dört: "appEmoji_dort",
        Beş: "appEmoji_bes",
        Alti: "appEmoji_alti",
        Yedi: "appEmoji_yedi",
        Sekiz: "appEmoji_sekiz",
        Dokuz: "appEmoji_dokuz",
        Sıfır: "appEmoji_sifir",
        Bot: "appEmoji_bot",
        Oynat: "appEmoji_oynat",
        Davet: "appEmoji_davet",
        Coin: "appEmoji_coin",
        Kalp: "appEmoji_kalp",
        Kiraz: "appEmoji_kiraz",
        Patlican: "appEmoji_patlican",
        Web: "appEmoji_web",
        Bilgisayar: "appEmoji_bilgisayar",
        Telefon: "appEmoji_telefon",
        Slot: "appEmoji_slot",
        Level: "appEmoji_level",
        Guard: "appEmoji_guard",
        OrtaBosBarGri: "appEmoji_obg",
        OrtaDoluBarYeşil: "appEmoji_oby",
        BaslangicBosBarGri: "appEmoji_bbg",
        BaslangicDoluBarYeşil: "appEmoji_bby",
        SonDoluBarYeşil: "appEmoji_sby",
        SonBosBarGri: "appEmoji_sbg",
        Oluştur: "appEmoji_create",
        Düzenle: "appEmoji_duzenle",
        Ekle: "appEmoji_ekle",
        Çıkar: "appEmoji_cikar",
        Gorunur: "appEmoji_gorunur",
        Görünmez: "appEmoji_gorunmez",
        KilitAçık: "appEmoji_kilidac",
        KilitKapalı: "appEmoji_kilitkapat",
        Ceza:"appEmoji_ceza"
    },
    default: [
        { name: "appEmoji_carpi", emoji: "❌" },
        { name: "appEmoji_tik", emoji: "✅" },
        { name: "appEmoji_unlem", emoji: "⚠" },
        { name: "appEmoji_kari", emoji: "👩" },
        { name: "appEmoji_erkek", emoji: "👨" },
        { name: "appEmoji_kategori", emoji: "🗃" },
        { name: "appEmoji_saat", emoji: "⏱" },
        { name: "appEmoji_elmas", emoji: "💎" },
        { name: "appEmoji_metin", emoji: "🗨" },
        { name: "appEmoji_ses", emoji: "🔉" },
        { name: "appEmoji_yayin", emoji: "🔴" },
        { name: "appEmoji_kamera", emoji: "📸" },
        { name: "appEmoji_kamera", emoji: "➡" },
        { name: "appEmoji_kamera", emoji: "⬅" },
        { name: "appEmoji_cop", emoji: "🗑" },
        { name: "appEmoji_kup", emoji: "🧊" },
        { name: "appEmoji_bir", emoji: "1️⃣" },
        { name: "appEmoji_iki", emoji: "2️⃣" },
        { name: "appEmoji_uc", emoji: "3️⃣" },
        { name: "appEmoji_dort", emoji: "4️⃣" },
        { name: "appEmoji_bes", emoji: "5️⃣" },
        { name: "appEmoji_alti", emoji: "6️⃣" },
        { name: "appEmoji_yedi", emoji: "7️⃣" },
        { name: "appEmoji_sekiz", emoji: "8️⃣" },
        { name: "appEmoji_dokuz", emoji: "9️⃣" },
        { name: "appEmoji_sifir", emoji: "0️⃣" },
        { name: "appEmoji_bot", emoji: "0️🤖" },
        { name: "appEmoji_oynat", emoji: "▶" },
        { name: "appEmoji_davet", emoji: "➕" },
        { name: "appEmoji_coin", emoji: "💰" },
        { name: "appEmoji_kalp", emoji: "❤" },
        { name: "appEmoji_kiraz", emoji: "🍒" },
        { name: "appEmoji_patlican", emoji: "🍆" },
        { name: "appEmoji_slot", emoji: "🎰" },
        { name: "appEmoji_web", emoji: "🌐" },
        { name: "appEmoji_bilgisayar", emoji: "🖥" },
        { name: "appEmoji_telefon", emoji: "📱" },
        { name: "appEmoji_level", emoji: "🆙" },
        { name: "appEmoji_guard", emoji: "🛡" },
        { name: "appEmoji_ceza", emoji: "🔨" },
        { name: "appEmoji_obg", emoji: "⬛" },
        { name: "appEmoji_oby", emoji: "🟩" },
        { name: "appEmoji_bbg", emoji: "⬛" },
        { name: "appEmoji_bby", emoji: "🟩" },
        { name: "appEmoji_sby", emoji: "🟩" },
        { name: "appEmoji_sbg", emoji: "⬛" },
        { name: "appEmoji_create", emoji: "🔊" },
        { name: "appEmoji_duzenle", emoji: "⚙" },
        { name: "appEmoji_ekle", emoji: "➕" },
        { name: "appEmoji_cikar", emoji: "➖" },
        { name: "appEmoji_gorunur", emoji: "🐵" },
        { name: "appEmoji_gorunmez", emoji: "🙈" },
        { name: "appEmoji_kilidac", emoji: "🔓" },
        { name: "appEmoji_kilitkapat", emoji: "🔏" },








    ]
}